spring:
  datasource:
	driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.17.0.2:3306/microservice
    username: root
    password: techbro@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect