spring:
  cloud:
    gateway:
      routes:
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE/
        predicates:
        - Path=/api/auth/**
      - id: DEMO-SERVICE
        uri: lb://DEMO-SERVICE/
        predicates:
        - Path=/api/demo/**
